global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['localhost:9090']

  - job_name: 'java-app-prometheus'
    dns_sd_configs:
      - names:
          - 'tasks.java-app'
        type: 'A'
        port: 8080
    metrics_path: '/prometheus'

  - job_name: 'java-app-metrics'
    dns_sd_configs:
      - names:
          - 'tasks.java-app'
        type: 'A'
        port: 8080
    metrics_path: '/metrics'
