# global:
#   scrape_interval: 15s
#   evaluation_interval: 15s

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']

#   - job_name: 'java-app'
#     metrics_path: /prometheus
#     static_configs:
#       - targets:
#           - 'java-app:8085'


global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-swarm-prometheus'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_task_service_name]
        target_label: job
      - source_labels: [__meta_dockerswarm_task_container_label_com_docker_swarm_service_name]
        target_label: container
      - source_labels: [__meta_dockerswarm_task_container_label_com_docker_swarm_node_id]
        target_label: node
      - source_labels: [__meta_dockerswarm_task_container_port]
        target_label: __address__
        regex: (.+);(.+)
        replacement: ${1}:${2}
